[package]
name = "mcservertest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.8.2"
rand = "0.8.5"
valence = { git = "https://github.com/valence-rs/valence" }
lazy_static = "1.4.0"

